# Generated by Django 2.0.4 on 2018-06-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_dias_emprestimo', models.IntegerField(verbose_name='Quantidade De Dias de Emprestimo')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data Emprestimo')),
                ('devolvido', models.BooleanField(default=False, verbose_name='Emprestimo Devolvido')),
                ('data_devolucao', models.DateTimeField(null=True, verbose_name='Data Devolução')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.FloatField(verbose_name='Preço Livro')),
                ('genero', models.CharField(max_length=255, verbose_name='Genero Livro')),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descricao')),
                ('autor', models.CharField(max_length=255, verbose_name='Autor')),
                ('quantidade_estoque', models.IntegerField(default=0, verbose_name='Quantidade Estoque')),
            ],
        ),
    ]
